routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth.sso']], function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('index');

   Route::group(['prefix' => 'branch', 'as' => 'branch.'], function () {
        Route::delete('destroy/{id}', 'BranchController@destroyBranch')->name('destroy');
        Route::put('detail/{id?}', 'BranchController@updateBranch')->name('update');
        Route::get('detail/{id?}', 'BranchController@showBranch')->name('detail');
        Route::post('store', 'BranchController@storeBranch')->name('store');
        Route::get('/', 'BranchController@showBranchList')->name('index'); 
    });

    Route::group(['prefix' => 'transaction', 'as' => 'transaction.'], function () {
        Route::group(['prefix' => 'service', 'as' => 'service.'], function () {
            Route::delete('destroy/{id}', 'TransactionController@destroyService')->name('destroy');
            Route::put('update/{id}', 'TransactionController@updateService')->name('update');
            Route::post('store', 'TransactionController@storeService')->name('store');
            Route::get('/', 'TransactionController@showServices')->name('index'); 
        });

        Route::post('store', 'TransactionController@storeDelivery')->name('store');
        Route::get('create', 'TransactionController@showDeliveryForm')->name('create');
        Route::patch('/{id}/action', 'TransactionController@handleDeliveryAction')->name('action');
        Route::get('/{id}/print', 'TransactionController@printDelivery')->name('print');
        Route::get('/{id}', 'TransactionController@showDelivery')->name('show');
        Route::get('/', 'TransactionController@index')->name('index');
    }); 
});

app/Models/Delivery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Delivery extends Model
{
    protected $table = 'deliveries';

    protected $primaryKey = 'id';

    protected $fillable = [
        'branch_id', 'user_id', 'receipt', 'bill_name', 'bill_address', 'bill_phone',
        'reciever_name', 'reciever_address', 'reciever_phone', 'total', 'status',
        'due_date',
    ];

    protected $dates = ['due_date'];

    const DELIV_STATUS = [
        'cancelled' => 0,
        'success' => 1,
        'process' => 2,
    ];

    public function getReceiptFormat()
    {
        return sprintf('#%s/%05d', Carbon::parse($this->attributes['created_at'])->format('Y/m/d'), $this->attributes['id']);
    }

    public function getStatusDisplayAttribute()
    {
        return array_flip(static::DELIV_STATUS)[$this->attributes['status']];
    }

    public function getLabelStatusDisplayAttribute()
    {
        switch ($this->attributes['status']) {
            case static::DELIV_STATUS['success']:
                $label = 'success';
                break;
            case static::DELIV_STATUS['process']:
                $label = 'info';
                break;
            default: $label = 'danger'; break;
        }
        return $label;
    }

    public function details()
    {
        return $this->hasMany(DeliveryDetail::class, 'delivery_id');
    }

    public function branch()
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }
}

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $table = 'services';

    protected $primaryKey = 'id';

    protected $fillable = [
        'name', 'status', 'price',
    ];

    protected $appends = [
        'fullname_display',
    ];

    const STATUS = [
        'inactive' => 0,
        'active' => 1,
    ];

    public function getStatusDisplayAttribute()
    {
        return array_search($this->attributes['status'], static::STATUS);
    }

    public function getFullnameDisplayAttribute()
    {
        return "{$this->attributes['name']} - " . formatRp($this->attributes['price']);
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Service;
use App\Models\Delivery;
use Illuminate\Http\Request;
use App\Http\Requests\DeliveryRequest;
use App\Http\Requests\HandleServiceRequest;
use Illuminate\Support\Facades\DB;

class TransactionController extends Controller
{
    protected $delivery_action = ['success', 'cancelled'];

    public function index(Request $request)
    {
        $deliveries = Delivery::withCount('details')->latest();

        $offset = (int) $request->input('page', 1);
        $offset = $offset > 1 ? ($offset - 1) * 15 : 0;

        $params = $request->only(['status', 'branch', 'keyword']);

        $data['delivery_action'] = $this->delivery_action;

        $data['offset'] = $offset + 1;
        $data['params'] = $params;
        $data['deliveries'] = $deliveries->paginate()->appends($params);
        $data['title'] = trans('page/transaction.delivery.title');
        // return $data;
        return view('site.pages.transaction.delivery', $data);
    }

    public function showDeliveryForm()
    {
        $data['title'] = trans('page/transaction.delivery.section.add');
        return view('site.pages.transaction.delivery_form', $data);
    }

    public function storeDelivery(DeliveryRequest $request)
    {
        $created = DB::transaction(function() use($request){
            $delivery = Delivery::create([
                'branch_id' => $request->input('branch'),
                'user_id' => null,
                'bill_name' => $request->input('bill_name'),
                'bill_address' => $request->input('bill_address'),
                'bill_phone' => $request->input('bill_phone'),
                'reciever_name' => $request->input('reciever_name'),
                'reciever_address' => $request->input('reciever_address'),
                'reciever_phone' => $request->input('reciever_phone'),
                'due_date' => \Carbon\Carbon::parse($request->input('due_date')),
                'status' => Delivery::DELIV_STATUS['process'],
            ]);
            $delivery->details()->createMany($request->input('details'));
            $delivery->update([
                'receipt' => $delivery->getReceiptFormat(),
                'total' => (int) str_replace('.', '', $request->input('total')),
            ]);
            return $delivery;
        });
        if($created){
            $request->session()->flash('flash_messages', ['success' => trans('messages.success.delivery.created')]);
            return redirect()->route('transaction.show', ['id' => $created->id]);
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.delivery.failed_create')]);
            return redirect()->back()->withInput();
        }
    }

    public function showDelivery($id)
    {
        $delivery = Delivery::with([
            'branch:id,agent_id,name,address,phone,fax',
            'branch.agent:id,name',
            'details'
        ])->find($id);

        $data['delivery_action'] = $this->delivery_action;

        $data['delivery'] = $delivery;
        $data['title'] = trans_choice('page/transaction.delivery.section.detail', !empty($delivery), [
            'invoice' => $delivery ? $delivery->receipt : null
        ]);
        // return $data;
        return view('site.pages.transaction.delivery_detail', $data);
    }

    public function handleDeliveryAction(Request $request, $id)
    {
        $delivery = Delivery::with([
            'branch:id,agent_id,name,address,phone,fax',
            'branch.agent:id,name',
        ])->find($id);

        if (!empty($delivery)) {
            $this->validate($request, [
                'action' => 'required|string|in:' . implode(',', $this->delivery_action),
            ]);
            $messages = [];
            $update = [];

            if ($delivery->status == Delivery::DELIV_STATUS['process']) {
                $update['status'] = Delivery::DELIV_STATUS[$request->input('action')];
                if ($delivery->update($update)) {
                    $messages['success'][] = trans('messages.success.delivery.updated', ['invoice' => $delivery->receipt]);
                }
            }else{
                $messages['errors'][] = trans('messages.errors.delivery.already_' . $request->input('action'));
            }
            $request->session()->flash('flash_messages', $messages);
        }else{
            $request->session()->flash('flash_messages', [
                'errors' => trans('messages.errors.not_found', true, ['item' => trans('page/transaction.delivery.title')])
            ]);
        }
        return redirect()->back();
    }

    public function printDelivery($id)
    {
        $delivery = Delivery::with([
            'branch:id,agent_id,name,address,phone,fax',
            'branch.agent:id,name',
            'details'
        ])->find($id);

        if (!empty($delivery)) {
            return view('site.pages.transaction.delivery_print',compact('delivery'));
        }

        request()->session()->flash('flash_messages', [
            'errors' => trans('messages.errors.not_found', true, ['item' => trans('page/transaction.delivery.title')])
        ]);
        return redirect()->route('transaction.index');
    }

    public function showServices(Request $request)
    {
        $services = Service::latest();

        $offset = (int) $request->input('page', 1);
        $offset = $offset > 1 ? ($offset - 1) * 15 : 0;

        // check jika sebelumnya merequest update dari validasi gagal.
        $servicedata = Service::find(session('service_id'));

        $data['offset'] = $offset + 1;
        $data['servicedata'] = $servicedata;
        $data['services'] = $services->paginate()->appends([]);
        $data['title'] = trans('page/transaction.service.title');
        return view('site.pages.transaction.services', $data);
    }

    public function storeService(HandleServiceRequest $request)
    {
        $service = new Service($request->only([
            'name', 'price', 'status'
        ]));
        if ($service->save()) {
            $request->session()->flash('flash_messages', ['success' => trans('messages.success.service.created')]);
            return redirect()->route('transaction.service.index');
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.success.service.failed_create')]);
        }
        return redirect()->back();
    }

    public function updateService(HandleServiceRequest $request, $id)
    {
        $service = Service::find($id);
        if (!empty($service)) {
            $saved = $service->update($request->only([
                'name', 'price', 'status'
            ]));
            if ($saved) {
                $request->session()->flash('flash_messages', ['success' => trans('messages.success.service.updated')]);
                return redirect()->route('transaction.service.index');
            }else{
                $request->session()->flash('flash_messages', ['errors' => trans('messages.success.service.failed_update')]);
            }
        }else{
            $request->session()->flash('flash_messages', [
                'errors' => trans('messages.errors.not_found', ['item' => trans('page/transaction.service.title')])
            ]);
            return redirect()->back();
        }
    }

    public function destroyService(Request $request, $id)
    {
        $messages = [];
        $service = Service::find($id);
        if (!empty($service)) {
            if ($service->delete()) {
                $messages['success'][] = trans('messages.success.service.deleted');
            }else{
                $messages['errors'][] = trans('messages.errors.service.failed_delete');
            }
        }else{
            $messages['errors'][] = trans('messages.errors.not_found', [
                'item' => trans('page/transaction.service.title')
            ]);
        }
        $request->session()->flash('flash_messages', $messages);
        return redirect()->back();
    }
}

resources/views/site/pages/transaction/delivery.blade.php
@extends('site.layouts.app')
@section('content')
    @component('site.layouts.page_header')
        @slot('title') {{ $title }} @endslot
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('transaction.create') }}">
                <i class="fa fa-plus"></i> @lang('page/transaction.delivery.section.add')
            </a>
        </div>
    @endcomponent
    @includeWhen(session('flash_messages'), 'site.layouts.feedback')
    <div class="panel-group" id="filter-group">
        <div class="panel">
            <div class="panel-heading">
                <a class="accordion-toggle {{ !empty($params) ? 'collapsed' : 'collapse' }}" data-toggle="collapse" href="#collapseFilter" data-parent="#filter-group">@lang('page/transaction.delivery.section.filter')</a>
            </div>
            <div id="collapseFilter" class="panel-collapse collapse {{ !empty($params) ? 'in' : '' }}">
                <div class="panel-body">
                </div>
            </div>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">@lang('page/transaction.delivery.description')</span>
        </div>
        <div class="panel-body with-margins">
            <div class="table-primary table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 10px;">#</th>
                            <th style="width: 140px;">@lang('page/transaction.delivery.field.invoice')</th>
                            <th>@lang('page/transaction.delivery.field.bill_name')</th>
                            <th>@lang('page/transaction.delivery.field.reciever_name')</th>
                            <th style="width: 130px;">@lang('page/transaction.delivery.field.total')</th>
                            <th>@lang('page/transaction.delivery.field.status.title')</th>
                            <th style="width: 140px;">@lang('page/transaction.delivery.field.created_at')</th>
                            <th style="width: 140px;">@lang('page/transaction.delivery.field.due_date')</th>
                            <th style="width: 100px;">@lang('layout.text.action')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($deliveries as $delivery)
                            <tr>
                                <td>{{ $offset++ }}</td>
                                <td>
                                    <a href="{{ route('transaction.show', ['id' => $delivery->id]) }}">{{ $delivery->receipt }}</a>
                                </td>
                                <td>{{ $delivery->bill_name }}</td>
                                <td>{{ $delivery->reciever_name }}</td>
                                <td>{{ formatRp($delivery->total) }}</td>
                                <td class="text-center">
                                    <span class="label label-{{ $delivery->label_status_display }}">{{ trans('page/transaction.delivery.field.status.' . $delivery->status_display) }}</span>
                                </td>
                                <td>{{ $delivery->created_at->format('H:i - d F Y') }}</td>
                                <td>{{ $delivery->due_date->format('H:i - d F Y') }}</td>
                                <td class="text-center">
                                    <a href="{{ route('transaction.show', ['id' => $delivery->id]) }}" class="btn btn-primary" data-toggle="tooltip" title="{{ trans('page/transaction.delivery.section.detail') }}" data-placement="top"><i class="fa fa-search"></i></a>
                                    @if ($delivery->status == $delivery_status['process'])
                                        @foreach ($delivery_action as $action)
                                            {{ Form::open([
                                                'route' => ['transaction.action', $delivery->id],
                                                'method' => 'patch',
                                                'style' => 'display: inline;'
                                            ]) }}
                                                <input type="hidden" name="action" value="{{ $action }}">
                                                <button type="button" class="btn btn-{{ $action == 'success' ? 'success' : 'danger' }} confirm-modal" data-message="{{ trans('page/transaction.delivery.text.confirm_' . $action) }}">
                                                    <i class="fa fa-{{ $action == 'success' ? 'check' : 'times' }}"></i>
                                                </button>
                                            {{ Form::close() }}
                                        @endforeach
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="9" align="center">{{ trans('messages.errors.empty_data') }}</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="pull-right">
                {!! $deliveries->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/site/pages/transaction/delivery_detail.blade.php
@extends('site.layouts.app')
@section('content')
    @component('site.layouts.page_header')
        @slot('title') {{ $title }} @endslot
        @if (!empty($delivery))
            <div class="pull-right">
                <a href="{{ url()->previous() != url()->current() ? url()->previous() : route('transaction.index') }}" class="btn btn-default">@lang('layout.buttons.back')</a>
                @if ($delivery->status == $delivery_status['process'])
                    @foreach ($delivery_action as $action)
                        {{ Form::open([
                            'route' => ['transaction.action', $delivery->id],
                            'method' => 'patch',
                            'style' => 'display: inline;'
                        ]) }}
                            <input type="hidden" name="action" value="{{ $action }}">
                            <button type="button" class="btn btn-{{ $action == 'success' ? 'success' : 'danger' }} confirm-modal" data-message="{{ trans('page/transaction.delivery.text.confirm_' . $action) }}">
                                <i class="fa fa-{{ $action == 'success' ? 'check' : 'times' }}"></i> @lang('page/transaction.delivery.buttons.' . $action)
                            </button>
                        {{ Form::close() }}
                    @endforeach
                @endif
                <a href="{{ route('transaction.print', ['id' => $delivery->id]) }}" class="btn btn-primary" target="_blank"><i class="fa fa-print"></i>&nbsp;&nbsp;@lang('page/transaction.delivery.text.print')</a>
            </div>
        @endif
    @endcomponent
    @includeWhen(session('flash_messages'), 'site.layouts.feedback')
    @if (!empty($delivery))
        <div class="panel invoice">
            <div class="invoice-header">
                <h3>
                    <div class="invoice-logo demo-logo"><img src="{{ asset('assets/logo.png') }}" alt="" style="width:100%;height:100%;"></div>
                    <div>
                        <small><strong>{{ config('app.name') }}</strong></small><br>
                        {{ trans('page/transaction.delivery.field.invoice').' '.$delivery->receipt }}
                    </div>
                    {{-- <div>
                        <span class="label label-{{ $delivery->label_status_display }}">{{ trans('page/transaction.delivery.field.status.' . $delivery->status_display) }}</span>
                    </div> --}}
                </h3>
                <address>
                    {{ $delivery->branch->name }}<br>
                    {!! nl2br($delivery->branch->address) !!}<br>
                    {{ $delivery->branch->phone }}
                </address>
                <div class="invoice-date">
                    <small><strong>@lang('page/transaction.delivery.field.due_date')</strong></small><br>
                    {{ $delivery->due_date->format('d F Y') }}
                </div>
                <div class="invoice-date" style="margin-right: 10rem;">
                    <small><strong>@lang('page/transaction.delivery.field.created_at')</strong></small><br>
                    {{ $delivery->created_at->format('H:i - d F Y') }}
                </div>
            </div>
            <div class="invoice-info">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <table>
                                <thead>
                                    <tr><th>@lang('page/transaction.delivery.field.bill_name')</th></tr>
                                </thead>
                                <tbody>
                                    <tr><td><strong>{{ $delivery->bill_name }}</strong></td></tr>
                                    <tr><td>{!! nl2br($delivery->bill_address) !!}</td></tr>
                                    <tr><td>{{ $delivery->bill_phone }}</td></tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table>
                                <thead>
                                    <tr><th>@lang('page/transaction.delivery.field.reciever_name')</th></tr>
                                </thead>
                                <tbody>
                                    <tr><td><strong>{{ $delivery->reciever_name }}</strong></td></tr>
                                    <tr><td>{!! nl2br($delivery->reciever_address) !!}</td></tr>
                                    <tr><td>{{ $delivery->reciever_phone }}</td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="invoice-table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>@lang('page/transaction.delivery.field.detail.description')</th>
                            <th class="text-right">@lang('page/transaction.delivery.field.detail.qty')</th>
                            <th class="text-right">@lang('page/transaction.delivery.field.detail.weight')</th>
                            <th class="text-right">@lang('page/transaction.delivery.field.detail.price')</th>
                            <th class="text-right">@lang('page/transaction.delivery.field.detail.subtotal')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($delivery->details as $detail)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    {{ nl2br($detail->description) }}
                                    {{-- <div class="invoice-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</div> --}}
                                </td>
                                <td class="text-right">{{ $detail->qty }}</td>
                                <td class="text-right">{{ $detail->weight }}</td>
                                <td class="text-right">{{ formatRp($detail->price) }}</td>
                                <td class="text-right">{{ formatRp($detail->qty * $detail->price) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <hr>
            <div class="invoice-info">
                <div class="invoice-total">
                    <span>{{ formatRp($delivery->total) }}</span>
                    @lang('page/transaction.delivery.field.total') :
                </div>
            </div>
        </div>
    @else
        @include('site.pages.notfound', ['route' => route('transaction.index')])
    @endif
@endsection

resources/views/site/pages/transaction/services.blade.php
@extends('site.layouts.app')
@section('content')
    @component('site.layouts.page_header')
        @slot('title') {{ $title }} @endslot
        <div class="pull-right">
            <button class="btn btn-primary handler-modal" data-toggle="modal" data-target="#form-modal" data-type="add" data-url="{{ route("transaction.service.store") }}" data-title="@lang('page/transaction.service.section.add')" data-section="service">
                <i class="fa fa-plus"></i> @lang('page/transaction.service.section.add')
            </button>
        </div>
    @endcomponent
    @includeWhen(session('flash_messages'), 'site.layouts.feedback')
    <div class="row">
        <div class="col-md-9 col-xs-offset-1">
            <div class="panel">
                <div class="panel-heading">
                    <span class="panel-title">@lang('page/transaction.service.description')</span>
                </div>
                <div class="panel-body with-margins">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-primary">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px;">#</th>
                                            <th>@lang('page/transaction.service.field.name')</th>
                                            <th>@lang('page/transaction.service.field.price')</th>
                                            <th style="width: 100px;">@lang('page/transaction.service.field.status.title')</th>
                                            <th style="width: 100px;">@lang('layout.text.action')</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($services as $service)
                                            <tr>
                                                <td>{{ $offset++ }}</td>
                                                <td>{{ $service->name }}</td>
                                                <td>{{ format_currency($service->price) }}</td>
                                                <td class="text-center">
                                                    <span class="label label-{{ $service->status ? 'success' : 'danger' }}">{{ trans('page/transaction.service.field.status.' . $service->status_display) }}</span>
                                                </td>
                                                <td>
                                                    <button class="btn btn-primary handler-modal" data-toggle="modal" data-target="#form-modal" data-valuedata='{!! $service !!}' data-type="edit" data-url="{{ route('transaction.service.update', ['id' => $service->id]) }}" data-title="@lang('page/transaction.service.section.edit')" data-section="service"><i class="fa fa-pencil-square-o"></i></button>
                                                    {{ Form::open([
                                                        'method'=>'delete',
                                                        'route' => ['transaction.service.destroy', $service->id],
                                                        'style' => 'display:inline;'
                                                    ]) }}
                                                        <button type="button" class="btn btn-danger confirm-modal" data-message="{{ trans('page/transaction.service.text.confirm_delete') }}"><i class="fa fa-trash-o" data-toggle="tooltip" title="{{ trans_choice('common.buttons.delete', 0) }}" data-placement="top"></i></button>
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="5" align="center">{{ trans('messages.errors.empty_data') }}</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            {!! $services->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('html')
    @include('site.pages.transaction.service_modal', [
        'route' => $servicedata ? ['transaction.service.update', $servicedata->id] : 'transaction.service.store',
        'method' => $servicedata ? 'PUT' : 'POST',
        'modalTitle' => $servicedata ? trans('page/transaction.service.section.edit') : trans('page/transaction.service.section.add'),
        'servicedata' => $servicedata,
    ])
@endpush